### ISSUE TITLE
tsx support

### ISSUE THREAD

**Issue by tomaskallup** [maralla/completor-typescript#2]
Seems like this plugin doesn't work with the `tsx` extension, maybe because filetype becomes `typescript.tsx`? Is there something I could do about that?

**Comment by maralla** [comment]
You can add the config to your vimrc:
```vim
let g:completor_filetype_map = {'typescript.tsx': 'typescript'}
```
Or you can update both completor and completor-typescript to the latest commit.

**Comment by tomaskallup** [comment]
Sorry for holdup, this issue was resolved
